if SERVER then
	concommand.Add("radvoice", function(ply, _, args)
		local path = glon.decode(args[1])
		ply:EmitSound(path:gsub([[\]], [[/]]), 100, math.random(97,103))
	end)
return end

local middle = "Ready"
local words = {   
   "Negative",
   "Taunt",
   "Laughter",

   "Thanks",
   "Hurrah",
   "Yes",
   "Sorry",
   "No",
}

local voices = {
	"biker",
	"manager",
	"namvet",
	"teengirl",

	"coach",
	"gambler",
	"mechanic",
	"producer",
}

local tbl = 
{
["Taunt"] = {
	[1] = "player/survivor/voice/biker/Taunt01.wav",
	[2] = "player/survivor/voice/biker/Taunt02.wav",
	[3] = "player/survivor/voice/biker/Taunt03.wav",
	[4] = "player/survivor/voice/biker/Taunt04.wav",
	[5] = "player/survivor/voice/biker/Taunt05.wav",
	[6] = "player/survivor/voice/biker/Taunt06.wav",
	[7] = "player/survivor/voice/biker/Taunt07.wav",
	[8] = "player/survivor/voice/biker/Taunt08.wav",
	[9] = "player/survivor/voice/biker/Taunt09.wav",
	[10] = "player/survivor/voice/biker/Taunt10.wav",
	[11] = "player/survivor/voice/manager/Taunt01.wav",
	[12] = "player/survivor/voice/manager/Taunt02.wav",
	[13] = "player/survivor/voice/manager/Taunt03.wav",
	[14] = "player/survivor/voice/manager/Taunt04.wav",
	[15] = "player/survivor/voice/manager/Taunt05.wav",
	[16] = "player/survivor/voice/manager/Taunt06.wav",
	[17] = "player/survivor/voice/manager/Taunt07.wav",
	[18] = "player/survivor/voice/manager/Taunt08.wav",
	[19] = "player/survivor/voice/manager/Taunt09.wav",
	[20] = "player/survivor/voice/manager/Taunt10.wav",
	[21] = "player/survivor/voice/namvet/Taunt01.wav",
	[22] = "player/survivor/voice/namvet/Taunt02.wav",
	[23] = "player/survivor/voice/namvet/Taunt07.wav",
	[24] = "player/survivor/voice/namvet/Taunt08.wav",
	[25] = "player/survivor/voice/namvet/Taunt09.wav",
	[26] = "player/survivor/voice/teengirl/Taunt02.wav",
	[27] = "player/survivor/voice/teengirl/Taunt13.wav",
	[28] = "player/survivor/voice/teengirl/Taunt18.wav",
	[29] = "player/survivor/voice/teengirl/Taunt19.wav",
	[30] = "player/survivor/voice/teengirl/Taunt20.wav",
	[31] = "player/survivor/voice/teengirl/Taunt21.wav",
	[32] = "player/survivor/voice/teengirl/Taunt24.wav",
	[33] = "player/survivor/voice/teengirl/Taunt25.wav",
	[34] = "player/survivor/voice/teengirl/Taunt26.wav",
	[35] = "player/survivor/voice/teengirl/Taunt28.wav",
	[36] = "player/survivor/voice/teengirl/Taunt29.wav",
	[37] = "player/survivor/voice/teengirl/Taunt30.wav",
	[38] = "player/survivor/voice/teengirl/Taunt31.wav",
	[39] = "player/survivor/voice/teengirl/Taunt34.wav",
	[40] = "player/survivor/voice/teengirl/Taunt35.wav",
	[41] = "player/survivor/voice/teengirl/Taunt39.wav",
},
["Sorry"] = {
	[1] = "player/survivor/voice/biker/Sorry01.wav",
	[2] = "player/survivor/voice/biker/Sorry02.wav",
	[3] = "player/survivor/voice/biker/Sorry03.wav",
	[4] = "player/survivor/voice/biker/Sorry04.wav",
	[5] = "player/survivor/voice/biker/Sorry05.wav",
	[6] = "player/survivor/voice/biker/Sorry06.wav",
	[7] = "player/survivor/voice/biker/Sorry07.wav",
	[8] = "player/survivor/voice/biker/Sorry08.wav",
	[9] = "player/survivor/voice/biker/Sorry09.wav",
	[10] = "player/survivor/voice/biker/Sorry10.wav",
	[11] = "player/survivor/voice/biker/Sorry12.wav",
	[12] = "player/survivor/voice/biker/Sorry13.wav",
	[13] = "player/survivor/voice/biker/Sorry14.wav",
	[14] = "player/survivor/voice/biker/Sorry15.wav",
	[15] = "player/survivor/voice/biker/Sorry16.wav",
	[16] = "player/survivor/voice/biker/Sorry17.wav",
	[17] = "player/survivor/voice/biker/Sorry18.wav",
	[18] = "player/survivor/voice/manager/Sorry01.wav",
	[19] = "player/survivor/voice/manager/Sorry02.wav",
	[20] = "player/survivor/voice/manager/Sorry03.wav",
	[21] = "player/survivor/voice/manager/Sorry04.wav",
	[22] = "player/survivor/voice/manager/Sorry06.wav",
	[23] = "player/survivor/voice/manager/Sorry07.wav",
	[24] = "player/survivor/voice/namvet/Sorry01.wav",
	[25] = "player/survivor/voice/namvet/Sorry02.wav",
	[26] = "player/survivor/voice/namvet/Sorry03.wav",
	[27] = "player/survivor/voice/namvet/Sorry04.wav",
	[28] = "player/survivor/voice/namvet/Sorry05.wav",
	[29] = "player/survivor/voice/namvet/Sorry07.wav",
	[30] = "player/survivor/voice/namvet/Sorry08.wav",
	[31] = "player/survivor/voice/namvet/Sorry09.wav",
	[32] = "player/survivor/voice/namvet/Sorry10.wav",
	[33] = "player/survivor/voice/namvet/Sorry11.wav",
	[34] = "player/survivor/voice/namvet/Sorry12.wav",
	[35] = "player/survivor/voice/teengirl/Sorry04.wav",
	[36] = "player/survivor/voice/teengirl/Sorry05.wav",
	[37] = "player/survivor/voice/teengirl/Sorry06.wav",
	[38] = "player/survivor/voice/teengirl/Sorry07.wav",
	[39] = "player/survivor/voice/teengirl/Sorry08.wav",
	[40] = "player/survivor/voice/teengirl/Sorry09.wav",
	[41] = "player/survivor/voice/teengirl/Sorry10.wav",
	[42] = "player/survivor/voice/teengirl/Sorry11.wav",
	[43] = "player/survivor/voice/teengirl/Sorry12.wav",
	[44] = "player/survivor/voice/teengirl/Sorry13.wav",
	[45] = "player/survivor/voice/teengirl/Sorry14.wav",
	[46] = "player/survivor/voice/teengirl/Sorry15.wav",
	[47] = "player/survivor/voice/teengirl/Sorry16.wav",
	[48] = "player/survivor/voice/teengirl/Sorry17.wav",
	[49] = "player/survivor/voice/teengirl/Sorry18.wav",
	[50] = "player/survivor/voice/teengirl/Sorry20.wav",
	[51] = "player/survivor/voice/teengirl/Sorry23.wav",
},
["Laughter"] = {
	[1] = "player/survivor/voice/biker/Laughter01.wav",
	[2] = "player/survivor/voice/biker/Laughter02.wav",
	[3] = "player/survivor/voice/biker/Laughter03.wav",
	[4] = "player/survivor/voice/biker/Laughter04.wav",
	[5] = "player/survivor/voice/biker/Laughter05.wav",
	[6] = "player/survivor/voice/biker/Laughter06.wav",
	[7] = "player/survivor/voice/biker/Laughter07.wav",
	[8] = "player/survivor/voice/biker/Laughter08.wav",
	[9] = "player/survivor/voice/biker/Laughter09.wav",
	[10] = "player/survivor/voice/biker/Laughter10.wav",
	[11] = "player/survivor/voice/biker/Laughter11.wav",
	[12] = "player/survivor/voice/biker/Laughter12.wav",
	[13] = "player/survivor/voice/biker/Laughter13.wav",
	[14] = "player/survivor/voice/biker/Laughter14.wav",
	[15] = "player/survivor/voice/biker/Laughter15.wav",
	[16] = "player/survivor/voice/manager/Laughter01.wav",
	[17] = "player/survivor/voice/manager/Laughter02.wav",
	[18] = "player/survivor/voice/manager/Laughter03.wav",
	[19] = "player/survivor/voice/manager/Laughter04.wav",
	[20] = "player/survivor/voice/manager/Laughter05.wav",
	[21] = "player/survivor/voice/manager/Laughter06.wav",
	[22] = "player/survivor/voice/manager/Laughter07.wav",
	[23] = "player/survivor/voice/manager/Laughter08.wav",
	[24] = "player/survivor/voice/manager/Laughter09.wav",
	[25] = "player/survivor/voice/manager/Laughter10.wav",
	[26] = "player/survivor/voice/manager/Laughter11.wav",
	[27] = "player/survivor/voice/manager/Laughter12.wav",
	[28] = "player/survivor/voice/manager/Laughter13.wav",
	[29] = "player/survivor/voice/manager/Laughter14.wav",
	[30] = "player/survivor/voice/manager/Laughter15.wav",
	[31] = "player/survivor/voice/manager/Laughter16.wav",
	[32] = "player/survivor/voice/manager/Laughter17.wav",
	[33] = "player/survivor/voice/manager/Laughter18.wav",
	[34] = "player/survivor/voice/manager/Laughter19.wav",
	[35] = "player/survivor/voice/manager/Laughter20.wav",
	[36] = "player/survivor/voice/manager/Laughter21.wav",
	[37] = "player/survivor/voice/namvet/Laughter01.wav",
	[38] = "player/survivor/voice/namvet/Laughter02.wav",
	[39] = "player/survivor/voice/namvet/Laughter04.wav",
	[40] = "player/survivor/voice/namvet/Laughter05.wav",
	[41] = "player/survivor/voice/namvet/Laughter06.wav",
	[42] = "player/survivor/voice/namvet/Laughter07.wav",
	[43] = "player/survivor/voice/namvet/Laughter08.wav",
	[44] = "player/survivor/voice/namvet/Laughter09.wav",
	[45] = "player/survivor/voice/namvet/Laughter10.wav",
	[46] = "player/survivor/voice/namvet/Laughter11.wav",
	[47] = "player/survivor/voice/namvet/Laughter12.wav",
	[48] = "player/survivor/voice/namvet/Laughter13.wav",
	[49] = "player/survivor/voice/namvet/Laughter14.wav",
	[50] = "player/survivor/voice/teengirl/Laughter01.wav",
	[51] = "player/survivor/voice/teengirl/Laughter02.wav",
	[52] = "player/survivor/voice/teengirl/Laughter03.wav",
	[53] = "player/survivor/voice/teengirl/Laughter04.wav",
	[54] = "player/survivor/voice/teengirl/Laughter05.wav",
	[55] = "player/survivor/voice/teengirl/Laughter06.wav",
	[56] = "player/survivor/voice/teengirl/Laughter07.wav",
	[57] = "player/survivor/voice/teengirl/Laughter08.wav",
	[58] = "player/survivor/voice/teengirl/Laughter09.wav",
	[59] = "player/survivor/voice/teengirl/Laughter10.wav",
	[60] = "player/survivor/voice/teengirl/Laughter11.wav",
	[61] = "player/survivor/voice/teengirl/Laughter12.wav",
	[62] = "player/survivor/voice/teengirl/Laughter13.wav",
	[63] = "player/survivor/voice/teengirl/Laughter14.wav",
	[64] = "player/survivor/voice/teengirl/Laughter15.wav",
	[65] = "player/survivor/voice/teengirl/Laughter16.wav",
	[66] = "player/survivor/voice/teengirl/Laughter17.wav",
	[67] = "player/survivor/voice/teengirl/Laughter18.wav",
	[68] = "player/survivor/voice/teengirl/Laughter19.wav",
	[69] = "player/survivor/voice/teengirl/Laughter20.wav",
	[70] = "player/survivor/voice/teengirl/Laughter21.wav",
},
["Thanks"] = {
	[1] = "player/survivor/voice/biker/Thanks01.wav",
	[2] = "player/survivor/voice/biker/Thanks02.wav",
	[3] = "player/survivor/voice/biker/Thanks03.wav",
	[4] = "player/survivor/voice/biker/Thanks04.wav",
	[5] = "player/survivor/voice/biker/Thanks05.wav",
	[6] = "player/survivor/voice/biker/Thanks06.wav",
	[7] = "player/survivor/voice/biker/Thanks07.wav",
	[8] = "player/survivor/voice/biker/Thanks08.wav",
	[9] = "player/survivor/voice/biker/Thanks09.wav",
	[10] = "player/survivor/voice/biker/Thanks10.wav",
	[11] = "player/survivor/voice/biker/Thanks11.wav",
	[12] = "player/survivor/voice/biker/Thanks12.wav",
	[13] = "player/survivor/voice/biker/Thanks13.wav",
	[14] = "player/survivor/voice/biker/Thanks14.wav",
	[15] = "player/survivor/voice/biker/Thanks15.wav",
	[16] = "player/survivor/voice/biker/Thanks16.wav",
	[17] = "player/survivor/voice/biker/Thanks17.wav",
	[18] = "player/survivor/voice/biker/Thanks18.wav",
	[19] = "player/survivor/voice/biker/Thanks19.wav",
	[20] = "player/survivor/voice/manager/Thanks01.wav",
	[21] = "player/survivor/voice/manager/Thanks02.wav",
	[22] = "player/survivor/voice/manager/Thanks03.wav",
	[23] = "player/survivor/voice/manager/Thanks04.wav",
	[24] = "player/survivor/voice/manager/Thanks05.wav",
	[25] = "player/survivor/voice/manager/Thanks06.wav",
	[26] = "player/survivor/voice/manager/Thanks07.wav",
	[27] = "player/survivor/voice/manager/Thanks08.wav",
	[28] = "player/survivor/voice/manager/Thanks09.wav",
	[29] = "player/survivor/voice/manager/Thanks10.wav",
	[30] = "player/survivor/voice/manager/Thanks11.wav",
	[31] = "player/survivor/voice/manager/Thanks12.wav",
	[32] = "player/survivor/voice/manager/Thanks13.wav",
	[33] = "player/survivor/voice/manager/Thanks14.wav",
	[34] = "player/survivor/voice/namvet/Thanks01.wav",
	[35] = "player/survivor/voice/namvet/Thanks02.wav",
	[36] = "player/survivor/voice/namvet/Thanks03.wav",
	[37] = "player/survivor/voice/namvet/Thanks04.wav",
	[38] = "player/survivor/voice/namvet/Thanks05.wav",
	[39] = "player/survivor/voice/namvet/Thanks06.wav",
	[40] = "player/survivor/voice/namvet/Thanks07.wav",
	[41] = "player/survivor/voice/namvet/Thanks08.wav",
	[42] = "player/survivor/voice/namvet/Thanks09.wav",
	[43] = "player/survivor/voice/namvet/Thanks10.wav",
	[44] = "player/survivor/voice/namvet/Thanks11.wav",
	[45] = "player/survivor/voice/teengirl/Thanks01.wav",
	[46] = "player/survivor/voice/teengirl/Thanks02.wav",
	[47] = "player/survivor/voice/teengirl/Thanks03.wav",
	[48] = "player/survivor/voice/teengirl/Thanks04.wav",
	[49] = "player/survivor/voice/teengirl/Thanks05.wav",
	[50] = "player/survivor/voice/teengirl/Thanks06.wav",
	[51] = "player/survivor/voice/teengirl/Thanks07.wav",
	[52] = "player/survivor/voice/teengirl/Thanks08.wav",
	[53] = "player/survivor/voice/teengirl/Thanks09.wav",
	[54] = "player/survivor/voice/teengirl/Thanks11.wav",
	[55] = "player/survivor/voice/teengirl/Thanks13.wav",
	[56] = "player/survivor/voice/teengirl/Thanks19.wav",
	[57] = "player/survivor/voice/teengirl/Thanks20.wav",
	[58] = "player/survivor/voice/teengirl/Thanks23.wav",
	[59] = "player/survivor/voice/teengirl/Thanks24.wav",
	[60] = "player/survivor/voice/teengirl/Thanks25.wav",
	[61] = "player/survivor/voice/teengirl/Thanks27.wav",
	[62] = "player/survivor/voice/teengirl/Thanks28.wav",
	[63] = "player/survivor/voice/teengirl/Thanks30.wav",
	[64] = "player/survivor/voice/teengirl/Thanks32.wav",
	[65] = "player/survivor/voice/teengirl/Thanks34.wav",
	[66] = "player/survivor/voice/teengirl/Thanks35.wav",
	[67] = "player/survivor/voice/teengirl/Thanks40.wav",
	[68] = "player/survivor/voice/teengirl/Thanks41.wav",
	[69] = "player/survivor/voice/teengirl/Thanks42.wav",
	[70] = "player/survivor/voice/teengirl/Thanks43.wav",
	[71] = "player/survivor/voice/teengirl/Thanks44.wav",
	[72] = "player/survivor/voice/teengirl/Thanks45.wav",
	[73] = "player/survivor/voice/teengirl/Thanks46.wav",
},
["Negative"] = {
	[1] = "player/survivor/voice/biker/ReactionNegative02.wav",
	[2] = "player/survivor/voice/biker/ReactionNegative03.wav",
	[3] = "player/survivor/voice/biker/ReactionNegative04.wav",
	[4] = "player/survivor/voice/biker/ReactionNegative05.wav",
	[5] = "player/survivor/voice/biker/ReactionNegative06.wav",
	[6] = "player/survivor/voice/biker/ReactionNegative07.wav",
	[7] = "player/survivor/voice/biker/ReactionNegative08.wav",
	[8] = "player/survivor/voice/biker/ReactionNegative09.wav",
	[9] = "player/survivor/voice/biker/ReactionNegative10.wav",
	[10] = "player/survivor/voice/manager/ReactionNegative01.wav",
	[11] = "player/survivor/voice/manager/ReactionNegative04.wav",
	[12] = "player/survivor/voice/namvet/ReactionNegative01.wav",
	[13] = "player/survivor/voice/namvet/ReactionNegative02.wav",
	[14] = "player/survivor/voice/namvet/ReactionNegative03.wav",
	[15] = "player/survivor/voice/namvet/ReactionNegative04.wav",
	[16] = "player/survivor/voice/namvet/ReactionNegative07.wav",
	[17] = "player/survivor/voice/namvet/ReactionNegative09.wav",
	[18] = "player/survivor/voice/namvet/ReactionNegative10.wav",
	[19] = "player/survivor/voice/namvet/ReactionNegative12.wav",
	[20] = "player/survivor/voice/teengirl/ReactionNegative01.wav",
	[21] = "player/survivor/voice/teengirl/ReactionNegative02.wav",
	[22] = "player/survivor/voice/teengirl/ReactionNegative03.wav",
	[23] = "player/survivor/voice/teengirl/ReactionNegative04.wav",
	[24] = "player/survivor/voice/teengirl/ReactionNegative05.wav",
	[25] = "player/survivor/voice/teengirl/ReactionNegative06.wav",
	[26] = "player/survivor/voice/teengirl/ReactionNegative08.wav",
	[27] = "player/survivor/voice/teengirl/ReactionNegative10.wav",
	[28] = "player/survivor/voice/teengirl/ReactionNegative11.wav",
	[29] = "player/survivor/voice/teengirl/ReactionNegative12.wav",
	[30] = "player/survivor/voice/teengirl/ReactionNegative14.wav",
	[31] = "player/survivor/voice/teengirl/ReactionNegative15.wav",
	[32] = "player/survivor/voice/teengirl/ReactionNegative16.wav",
	[33] = "player/survivor/voice/teengirl/ReactionNegative17.wav",
	[34] = "player/survivor/voice/teengirl/ReactionNegative18.wav",
	[35] = "player/survivor/voice/teengirl/ReactionNegative19.wav",
	[36] = "player/survivor/voice/teengirl/ReactionNegative21.wav",
	[37] = "player/survivor/voice/teengirl/ReactionNegative22.wav",
	[38] = "player/survivor/voice/teengirl/ReactionNegative23.wav",
	[39] = "player/survivor/voice/teengirl/ReactionNegative25.wav",
	[40] = "player/survivor/voice/teengirl/ReactionNegative26.wav",
	[41] = "player/survivor/voice/teengirl/ReactionNegative27.wav",
	[42] = "player/survivor/voice/teengirl/ReactionNegative28.wav",
	[43] = "player/survivor/voice/teengirl/ReactionNegative29.wav",
	[44] = "player/survivor/voice/teengirl/ReactionNegative31.wav",
	[45] = "player/survivor/voice/teengirl/ReactionNegative32.wav",
	[46] = "player/survivor/voice/teengirl/ReactionNegative33.wav",
},
["Ready"] = {
	[1] = "player/survivor/voice/coach/askready01.wav",
	[2] = "player/survivor/voice/coach/askready02.wav",
	[3] = "player/survivor/voice/coach/askready03.wav",
	[4] = "player/survivor/voice/coach/askready04.wav",
	[5] = "player/survivor/voice/coach/askready05.wav",
	[6] = "player/survivor/voice/coach/askready06.wav",
	[7] = "player/survivor/voice/coach/askready07.wav",
	[8] = "player/survivor/voice/coach/askready08.wav",
	[9] = "player/survivor/voice/coach/askready09.wav",
	[10] = "player/survivor/voice/gambler/askready01.wav",
	[11] = "player/survivor/voice/gambler/askready02.wav",
	[12] = "player/survivor/voice/gambler/askready03.wav",
	[13] = "player/survivor/voice/gambler/askready04.wav",
	[14] = "player/survivor/voice/gambler/askready05.wav",
	[15] = "player/survivor/voice/gambler/askready06.wav",
	[16] = "player/survivor/voice/gambler/askready07.wav",
	[17] = "player/survivor/voice/gambler/askready08.wav",
	[18] = "player/survivor/voice/gambler/askready09.wav",
	[19] = "player/survivor/voice/gambler/askready10.wav",
	[20] = "player/survivor/voice/mechanic/askready01.wav",
	[21] = "player/survivor/voice/mechanic/askready02.wav",
	[22] = "player/survivor/voice/mechanic/askready03.wav",
	[23] = "player/survivor/voice/producer/askready01.wav",
	[24] = "player/survivor/voice/producer/askready02.wav",
	[25] = "player/survivor/voice/producer/askready03.wav",
},
["Hurrah"] = {
	[1] = "player/survivor/voice/biker/Hurrah01.wav",
	[2] = "player/survivor/voice/biker/Hurrah02.wav",
	[3] = "player/survivor/voice/biker/Hurrah03.wav",
	[4] = "player/survivor/voice/biker/Hurrah04.wav",
	[5] = "player/survivor/voice/biker/Hurrah05.wav",
	[6] = "player/survivor/voice/biker/Hurrah06.wav",
	[7] = "player/survivor/voice/biker/Hurrah07.wav",
	[8] = "player/survivor/voice/biker/Hurrah08.wav",
	[9] = "player/survivor/voice/biker/Hurrah09.wav",
	[10] = "player/survivor/voice/biker/Hurrah10.wav",
	[11] = "player/survivor/voice/biker/Hurrah11.wav",
	[12] = "player/survivor/voice/biker/Hurrah12.wav",
	[13] = "player/survivor/voice/biker/Hurrah13.wav",
	[14] = "player/survivor/voice/biker/Hurrah14.wav",
	[15] = "player/survivor/voice/biker/Hurrah15.wav",
	[16] = "player/survivor/voice/biker/Hurrah16.wav",
	[17] = "player/survivor/voice/biker/Hurrah17.wav",
	[18] = "player/survivor/voice/biker/Hurrah18.wav",
	[19] = "player/survivor/voice/biker/Hurrah19.wav",
	[20] = "player/survivor/voice/biker/Hurrah20.wav",
	[21] = "player/survivor/voice/biker/Hurrah21.wav",
	[22] = "player/survivor/voice/biker/Hurrah22.wav",
	[23] = "player/survivor/voice/biker/Hurrah23.wav",
	[24] = "player/survivor/voice/biker/Hurrah24.wav",
	[25] = "player/survivor/voice/manager/Hurrah01.wav",
	[26] = "player/survivor/voice/manager/Hurrah02.wav",
	[27] = "player/survivor/voice/manager/Hurrah03.wav",
	[28] = "player/survivor/voice/manager/Hurrah05.wav",
	[29] = "player/survivor/voice/manager/Hurrah06.wav",
	[30] = "player/survivor/voice/manager/Hurrah07.wav",
	[31] = "player/survivor/voice/manager/Hurrah08.wav",
	[32] = "player/survivor/voice/manager/Hurrah09.wav",
	[33] = "player/survivor/voice/manager/Hurrah10.wav",
	[34] = "player/survivor/voice/manager/Hurrah11.wav",
	[35] = "player/survivor/voice/manager/Hurrah12.wav",
	[36] = "player/survivor/voice/manager/Hurrah13.wav",
	[37] = "player/survivor/voice/manager/Hurrah14.wav",
	[38] = "player/survivor/voice/manager/Hurrah15.wav",
	[39] = "player/survivor/voice/manager/Hurrah16.wav",
	[40] = "player/survivor/voice/namvet/Hurrah02.wav",
	[41] = "player/survivor/voice/namvet/Hurrah03.wav",
	[42] = "player/survivor/voice/namvet/Hurrah05.wav",
	[43] = "player/survivor/voice/namvet/Hurrah18.wav",
	[44] = "player/survivor/voice/namvet/Hurrah20.wav",
	[45] = "player/survivor/voice/teengirl/Hurrah01.wav",
	[46] = "player/survivor/voice/teengirl/Hurrah03.wav",
	[47] = "player/survivor/voice/teengirl/Hurrah04.wav",
	[48] = "player/survivor/voice/teengirl/Hurrah07.wav",
	[49] = "player/survivor/voice/teengirl/Hurrah08.wav",
	[50] = "player/survivor/voice/teengirl/Hurrah10.wav",
	[51] = "player/survivor/voice/teengirl/Hurrah11.wav",
	[52] = "player/survivor/voice/teengirl/Hurrah12.wav",
	[53] = "player/survivor/voice/teengirl/Hurrah13.wav",
	[54] = "player/survivor/voice/teengirl/Hurrah16.wav",
	[55] = "player/survivor/voice/teengirl/Hurrah17.wav",
	[56] = "player/survivor/voice/teengirl/Hurrah18.wav",
	[57] = "player/survivor/voice/teengirl/Hurrah19.wav",
	[58] = "player/survivor/voice/teengirl/Hurrah20.wav",
	[59] = "player/survivor/voice/teengirl/Hurrah22.wav",
	[60] = "player/survivor/voice/teengirl/Hurrah23.wav",
	[61] = "player/survivor/voice/teengirl/Hurrah31.wav",
	[62] = "player/survivor/voice/teengirl/Hurrah34.wav",
	[63] = "player/survivor/voice/teengirl/Hurrah35.wav",
	[64] = "player/survivor/voice/teengirl/Hurrah38.wav",
	[65] = "player/survivor/voice/teengirl/Hurrah46.wav",
	[66] = "player/survivor/voice/teengirl/Hurrah48.wav",
	[67] = "player/survivor/voice/teengirl/Hurrah51.wav",
	[68] = "player/survivor/voice/teengirl/Hurrah52.wav",
	[69] = "player/survivor/voice/teengirl/Hurrah53.wav",
	[70] = "player/survivor/voice/teengirl/Hurrah54.wav",
	[71] = "player/survivor/voice/teengirl/Hurrah55.wav",
	[72] = "player/survivor/voice/teengirl/Hurrah56.wav",
	[73] = "player/survivor/voice/teengirl/Hurrah57.wav",
	[74] = "player/survivor/voice/teengirl/Hurrah58.wav",
},
["Yes"] = {
	[1] = "player/survivor/voice/biker/Yes01.wav",
	[2] = "player/survivor/voice/biker/Yes02.wav",
	[3] = "player/survivor/voice/biker/Yes03.wav",
	[4] = "player/survivor/voice/biker/Yes04.wav",
	[5] = "player/survivor/voice/biker/Yes05.wav",
	[6] = "player/survivor/voice/biker/Yes06.wav",
	[7] = "player/survivor/voice/manager/Yes01.wav",
	[8] = "player/survivor/voice/manager/Yes02.wav",
	[9] = "player/survivor/voice/manager/Yes05.wav",
	[10] = "player/survivor/voice/manager/Yes07.wav",
	[11] = "player/survivor/voice/manager/Yes08.wav",
	[12] = "player/survivor/voice/manager/Yes09.wav",
	[13] = "player/survivor/voice/namvet/Yes02.wav",
	[14] = "player/survivor/voice/namvet/Yes03.wav",
	[15] = "player/survivor/voice/namvet/Yes04.wav",
	[16] = "player/survivor/voice/namvet/Yes05.wav",
	[17] = "player/survivor/voice/namvet/Yes06.wav",
	[18] = "player/survivor/voice/teengirl/Yes01.wav",
	[19] = "player/survivor/voice/teengirl/Yes02.wav",
	[20] = "player/survivor/voice/teengirl/Yes04.wav",
	[21] = "player/survivor/voice/teengirl/Yes05.wav",
	[22] = "player/survivor/voice/teengirl/Yes06.wav",
	[23] = "player/survivor/voice/teengirl/Yes08.wav",
	[24] = "player/survivor/voice/teengirl/Yes09.wav",
	[25] = "player/survivor/voice/teengirl/Yes10.wav",
	[26] = "player/survivor/voice/teengirl/Yes13.wav",
	[27] = "player/survivor/voice/teengirl/Yes14.wav",
	[28] = "player/survivor/voice/teengirl/Yes15.wav",
	[29] = "player/survivor/voice/teengirl/Yes16.wav",
	[30] = "player/survivor/voice/teengirl/Yes17.wav",
	[31] = "player/survivor/voice/teengirl/Yes18.wav",
},
["No"] = {
	[1] = "player/survivor/voice/biker/No01.wav",
	[2] = "player/survivor/voice/biker/No02.wav",
	[3] = "player/survivor/voice/biker/No03.wav",
	[4] = "player/survivor/voice/biker/No04.wav",
	[5] = "player/survivor/voice/biker/No05.wav",
	[6] = "player/survivor/voice/biker/No06.wav",
	[7] = "player/survivor/voice/biker/No07.wav",
	[8] = "player/survivor/voice/biker/No08.wav",
	[9] = "player/survivor/voice/biker/No09.wav",
	[10] = "player/survivor/voice/biker/No11.wav",
	[11] = "player/survivor/voice/biker/No12.wav",
	[12] = "player/survivor/voice/biker/No13.wav",
	[13] = "player/survivor/voice/biker/No14.wav",
	[14] = "player/survivor/voice/biker/No15.wav",
	[15] = "player/survivor/voice/biker/No16.wav",
	[16] = "player/survivor/voice/biker/No17.wav",
	[17] = "player/survivor/voice/biker/No18.wav",
	[18] = "player/survivor/voice/manager/No01.wav",
	[19] = "player/survivor/voice/manager/No02.wav",
	[20] = "player/survivor/voice/manager/No03.wav",
	[21] = "player/survivor/voice/manager/No04.wav",
	[22] = "player/survivor/voice/manager/No05.wav",
	[23] = "player/survivor/voice/manager/No08.wav",
	[24] = "player/survivor/voice/manager/No09.wav",
	[25] = "player/survivor/voice/namvet/No01.wav",
	[26] = "player/survivor/voice/namvet/No02.wav",
	[27] = "player/survivor/voice/namvet/No03.wav",
	[28] = "player/survivor/voice/namvet/No04.wav",
	[29] = "player/survivor/voice/namvet/No05.wav",
	[30] = "player/survivor/voice/namvet/No06.wav",
	[31] = "player/survivor/voice/namvet/No07.wav",
	[32] = "player/survivor/voice/namvet/No08.wav",
	[33] = "player/survivor/voice/namvet/No09.wav",
	[34] = "player/survivor/voice/namvet/No10.wav",
	[35] = "player/survivor/voice/namvet/No11.wav",
	[36] = "player/survivor/voice/namvet/No14.wav",
	[37] = "player/survivor/voice/namvet/No15.wav",
	[38] = "player/survivor/voice/teengirl/No01.wav",
	[39] = "player/survivor/voice/teengirl/No07.wav",
	[40] = "player/survivor/voice/teengirl/No08.wav",
	[41] = "player/survivor/voice/teengirl/No09.wav",
	[42] = "player/survivor/voice/teengirl/No10.wav",
	[43] = "player/survivor/voice/teengirl/No11.wav",
	[44] = "player/survivor/voice/teengirl/No14.wav",
	[45] = "player/survivor/voice/teengirl/No15.wav",
	[46] = "player/survivor/voice/teengirl/No18.wav",
	[47] = "player/survivor/voice/teengirl/No21.wav",
	[48] = "player/survivor/voice/teengirl/No22.wav",
	[49] = "player/survivor/voice/teengirl/No23.wav",
	[50] = "player/survivor/voice/teengirl/No24.wav",
	[51] = "player/survivor/voice/teengirl/No25.wav",
	[52] = "player/survivor/voice/teengirl/No31.wav",
	[53] = "player/survivor/voice/teengirl/No36.wav",
	[54] = "player/survivor/voice/teengirl/No38.wav",
	[55] = "player/survivor/voice/teengirl/No43.wav",
	[56] = "player/survivor/voice/teengirl/No48.wav",
	[57] = "player/survivor/voice/teengirl/No49.wav",
},

}

if false then
	local tbl = {}
	local _words = table.Copy(words)
	table.insert(_words, "askready")
	for _, voice in pairs(voices) do
		for _, word in pairs(_words) do
			for _, filename in pairs(file.Find("sound/player/survivor/voice/".. voice .."/" .. word .. "*.wav", true)) do
				if filename:sub(0,-7) == word or word == "Laugh" then
					tbl[word] = tbl[word] or {}
					table.insert(tbl[word], "player/survivor/voice/".. voice .."/" .. filename)
				end
			end
		end
	end 

	luadata.WriteFile("whatthehellman.txt", tbl)
end

local show = false

concommand.Add("+radial_voice_menu", function()
	show = true
	gui.EnableScreenClicker(show)
end)

concommand.Add("-radial_voice_menu", function()
	show = false
	gui.EnableScreenClicker(show)
end)

local function OnSelect(word)
   RunConsoleCommand("radvoice", glon.encode(table.Random(tbl[word])))
end

local count = #words
local radius = 11*count

local bounding = (200/8) 
local selected = false

local function DrawTextEx(txt,x,y,mx,my,ox,oy,i)
   local w,h = surface.GetTextSize(txt)  
   local distance = Vector(x,y,0):Distance(Vector(mx,my,0))

   surface.SetDrawColor(200,200,200,255)

   if distance < bounding then
      surface.DrawLine(Lerp(0.8, x, ox), Lerp(0.8, y, oy), Lerp(0.8,ox,x), Lerp(0.8,oy,y))
      surface.SetTextColor(255,255,255,255)


      if input.IsMouseDown(MOUSE_LEFT) then
         if not selected then
            OnSelect(txt)
            selected = true
         end
      else
         selected = false
      end
   else
      surface.SetTextColor(200,200,200,255)
   end

   x = x-(w*0.5)
   y = y-(h*0.5)

   surface.SetTextPos(x, y)
   surface.DrawText(txt)
end

local function Draw()
	if not show then return end
   if not vgui.CursorVisible() then show = false return end

   local x = ScrW()*0.5
   local y = ScrH()*0.5

   local mx = gui.MouseX()
   local my = gui.MouseY()

   surface.SetFont("targetid")
   surface.SetTextColor(255,255,255,100)

   DrawTextEx(middle, x, y, mx, my, x, y, 0)
   for i = 1, count do
      local txt = words[i]
      i = (i/count) * math.pi * 2
      DrawTextEx(txt, x+math.sin(i)*radius, y+math.cos(i)*radius, mx, my, x, y, i)
   end
end

hook.Add("HUDPaint","radial_l4d2", Draw)